// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HipHopPizzaNWings.Migrations
{
    [DbContext(typeof(HipHopPizzaNWingsDbContext))]
    partial class HipHopPizzaNWingsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HipHopPizzaNWings.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Large Pepperoni Pizza",
                            Price = 12.00m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Large Supreme Pizza",
                            Price = 14.00m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Large Cheese Pizza",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 4,
                            Name = "8 Piece Buffalo Wings",
                            Price = 7.00m
                        },
                        new
                        {
                            Id = 5,
                            Name = "12 Piece Buffalo Wings",
                            Price = 11.00m
                        });
                });

            modelBuilder.Entity("HipHopPizzaNWings.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Tip")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OrderTypeId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerName = "Mick Foley",
                            DateCreated = new DateTime(2024, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "JLee@email.com",
                            IsClosed = false,
                            OrderTypeId = 1,
                            PhoneNumber = "323-416-5523",
                            Subtotal = 0m,
                            Tip = 0m
                        },
                        new
                        {
                            Id = 2,
                            CustomerName = "Stan Hansen",
                            DateClosed = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "SHanson@email.com",
                            IsClosed = true,
                            OrderTypeId = 3,
                            PhoneNumber = "323-512-0833",
                            Subtotal = 23.00m,
                            Tip = 5.00m
                        },
                        new
                        {
                            Id = 3,
                            CustomerName = "Brody Lee",
                            DateCreated = new DateTime(2024, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "BrodyForever@email.com",
                            IsClosed = false,
                            OrderTypeId = 2,
                            PhoneNumber = "323-723-9376",
                            Subtotal = 0m,
                            Tip = 0m
                        });
                });

            modelBuilder.Entity("HipHopPizzaNWings.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("HipHopPizzaNWings.Models.OrderType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OrderTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Online"
                        },
                        new
                        {
                            Id = 2,
                            Type = "In Store"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Phone"
                        });
                });

            modelBuilder.Entity("HipHopPizzaNWings.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Uid = "06mu1mmHWrMad67XQeCBnKyYKPw1"
                        });
                });

            modelBuilder.Entity("HipHopPizzaNWings.Models.Order", b =>
                {
                    b.HasOne("HipHopPizzaNWings.Models.OrderType", "OrderType")
                        .WithMany()
                        .HasForeignKey("OrderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderType");
                });

            modelBuilder.Entity("HipHopPizzaNWings.Models.OrderItem", b =>
                {
                    b.HasOne("HipHopPizzaNWings.Models.Item", "Item")
                        .WithMany("Order")
                        .HasForeignKey("ItemId");

                    b.HasOne("HipHopPizzaNWings.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HipHopPizzaNWings.Models.Item", b =>
                {
                    b.Navigation("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
